version: '3'
services:
  db:
    image: mongo:7.0.5
    volumes:
      - ./.docker-compose/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
  app_dev:
    container_name: server_dev
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: runnerDev
    volumes:
      - .:/app/server
    ports:
      - ${APP_PORT}:${APP_PORT}
