version: '3'
services:
  db:
    image: mongo:7.0.5
    container_name: boo_server_mongo
    volumes:
      - ./.docker-compose/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    ports:
      - $MONGO_PORT:27017

  app_dev:
    container_name: boo_server_dev
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: runnerDev
    volumes:
      - .:/app/server
    ports:
      - $APP_PORT:$APP_PORT
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  app_test:
    container_name: boo_server_test
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: runnerDev
    command: sh -c "npm install && npm run test"
